# Start from a node image
FROM arm32v7/node:10
# Set the node environment variable to production
ENV NODE_ENV production
# Expose the default port 3000
EXPOSE 3000
# Set the working directory
WORKDIR /home/node/movie-night-app
# Copy all of the required files into the working directory
COPY [".", "."]
# Install all the required node packages
RUN npm install --only=prod
# Make a directory for the logs 
RUN mkdir logs
# Change the owner of the logs directory to the running user (node) so that it can be written into
RUN chown node logs
# Set the user as the node user
USER node
# Run the node command
CMD ["node", ".", "-o", "-c"]